Support s01e03 Follow Up
AfricasVoices/Project-WUSC-LEAP pull request #36
Opened 2021-03-15 13:59 UTC by DanielMwendwa

2021-03-15 15:29 UTC, as2388 requested changes
KeyError: "Code scheme 'KAKUMA WS - Correct Dataset' (id 'Scheme-fffffc6e') does not contain a code with match value 'leap kalobeyei girls empowerment'"

2021-03-15 15:59 UTC, DanielMwendwa commented on configurations/coding_plans.py
> +                       coding_mode=CodingModes.SINGLE,
Thanks, confirmed to be "multiple" and updated

2021-03-15 15:59 UTC, DanielMwendwa commented on configurations/coding_plans.py
> +                       fold_strategy=FoldStrategies.assert_label_ids_equal,
Thanks, updated

2021-03-15 16:01 UTC, DanielMwendwa commented
> fffffc6e

Resolved

2021-03-15 16:01 UTC, DanielMwendwa commented
> KeyError: "Code scheme 'KAKUMA WS - Correct Dataset' (id 'Scheme-fffffc6e') does not contain a code with match value 'leap kalobeyei girls empowerment'"

Resolved

2021-03-16 09:49 UTC, as2388 approved these changes

2021-03-16 09:53 UTC, merged